version: '2.1'

services:

  web:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    image: warmuprx:web
    ports:
      - "4000:4000"
    volumes:
      - ./shared:/var/www/virtual/warmuprx/shared
    links:
      - api
    depends_on:
      api:
        condition: service_healthy
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: docker/api.dockerfile
      args:
        app_root_path: /services
        app_mode: debug
        node_env: docker
    image: warmuprx:api
    command: nodemon --debug /services/server/server.js 5858
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - ./shared:/services/shared
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:3.0.7
    ports:
      - "28017:27017"
    volumes:
      - ./mount/mongo-v3.0.7:/data/db
    healthcheck:
      test: ["CMD", "/etc/init.d/mongod", "status"]
